artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/cb1c714d79ea4fad815419b2f27d5a56/artifacts
end_time: 1654604692434
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: cb1c714d79ea4fad815419b2f27d5a56
run_uuid: cb1c714d79ea4fad815419b2f27d5a56
source_name: ''
source_type: 4
source_version: ''
start_time: 1654604692392
status: 4
tags: []
user_id: samuel
