artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/416c08f86cac4ba09691be6d199caf4e/artifacts
end_time: 1654605619727
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 416c08f86cac4ba09691be6d199caf4e
run_uuid: 416c08f86cac4ba09691be6d199caf4e
source_name: ''
source_type: 4
source_version: ''
start_time: 1654605619686
status: 4
tags: []
user_id: samuel
