artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/104f5ee56e514649955d5c122a7a012a/artifacts
end_time: 1654604051820
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 104f5ee56e514649955d5c122a7a012a
run_uuid: 104f5ee56e514649955d5c122a7a012a
source_name: ''
source_type: 4
source_version: ''
start_time: 1654604050373
status: 3
tags: []
user_id: samuel
