artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/a4d9665b2e9a421f87dfb86d149413c5/artifacts
end_time: 1654604615423
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: a4d9665b2e9a421f87dfb86d149413c5
run_uuid: a4d9665b2e9a421f87dfb86d149413c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1654604615374
status: 4
tags: []
user_id: samuel
