artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/55df4d9feff34983acf324ec116cc162/artifacts
end_time: 1654605652954
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 55df4d9feff34983acf324ec116cc162
run_uuid: 55df4d9feff34983acf324ec116cc162
source_name: ''
source_type: 4
source_version: ''
start_time: 1654605652918
status: 4
tags: []
user_id: samuel
