artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/3da20dc4d8434c4f8fad87e9a2ceb24e/artifacts
end_time: 1654603912507
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 3da20dc4d8434c4f8fad87e9a2ceb24e
run_uuid: 3da20dc4d8434c4f8fad87e9a2ceb24e
source_name: ''
source_type: 4
source_version: ''
start_time: 1654603912487
status: 4
tags: []
user_id: samuel
