artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/7c14fa1b5d5447a6bd8ce159a6b072a5/artifacts
end_time: 1654605663763
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 7c14fa1b5d5447a6bd8ce159a6b072a5
run_uuid: 7c14fa1b5d5447a6bd8ce159a6b072a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1654605662466
status: 3
tags: []
user_id: samuel
