artifact_uri: file:///home/samuel/Documentos/Untitled%20Folder/ml_pipeline/mlops_lu/1/2baf86b0646c4adda3002ab7d161ccc0/artifacts
end_time: 1654604712683
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 2baf86b0646c4adda3002ab7d161ccc0
run_uuid: 2baf86b0646c4adda3002ab7d161ccc0
source_name: ''
source_type: 4
source_version: ''
start_time: 1654604712639
status: 4
tags: []
user_id: samuel
